# Trick to block the data_loader to prevent process exit before training done.(works for linux and macos)
data_loAder: persia-launcher data-loader data_loader.py --replica-index 0 --replica-size 1 && cat 
nn_worker: persia-launcher nn-worker train.py --nproc-per-node 1 --node-rank 0 --nnodes 1
embedding_worker: persia-launcher embedding-worker --embedding-config config/criteo_terabyte_embedding_config.yml  --global-config config/global_config.yml
embedding_server: persia-launcher embedding-parameter-server --embedding-config config/criteo_terabyte_embedding_config.yml --global-config config/global_config.yml
nats_server: nats-server
